return {
	["tp walk"] = "加速",
	["no clip"] = "穿墙",
	["esp"] = "透视",
	["track list"] = "跟踪列表",
	["track"] = "跟踪",
	["offset"] = "偏移",
	["player list"] = "玩家列表",
	["apply"] = "应用",
	["bullet start pos random"] = "弹道起始位置随机",
	["bullet end pos random"] = "弹道结束位置随机",
	["hit sound"] = "击中音效",
	["hit log"] = "击中日志",
	["silent block"] = "静默防御",
	["blade aura"] = "飞镖光环",
	["blatant"] = "暴力",
	["legit"] = "合法",
	["auto say"] = "自动发言",
    ["aimbot"] = "自瞄",
    ["fly"] = "飞行",
    ["universal"] = "通用",
    ["mode for aimbot"] = "自瞄模式",
    ["visual"] = "视觉",
    ["forcefield check"] = "忽略无敌",
    ["blade weapon"] = "飞镖武器",
    ["gun weapon"] = "枪械武器",
}
